#!/usr/bin/env bash
echo "== delete objects"

# check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1
aws s3api list-objects-v2 \
  --bucket "$BUCKET_NAME" \
  --query Contents[].Key \
| jq -n '{Objects: [inputs | .[] | {Key: .}]}'

aws s3api delete-objects \
  --bucket "$BUCKET_NAME" \
  --delete "$(aws s3api list-objects \
    --bucket "$BUCKET_NAME" \
    --query '{Objects: Contents[].{Key: Key}}')"


# aws s3api delete-objects \
# --bucket $BUCKET_NAME \
# --delete file:///tmp/delete_objects.json
